# Generated by Django 3.1.4 on 2021-01-24 15:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=150, verbose_name='Banner Group')),
                ('status', models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], max_length=10)),
                ('caption', models.CharField(max_length=150, verbose_name='Title')),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nigne', max_length=150, null=True)),
                ('keywords', models.CharField(default=' ', max_length=255, null=True)),
                ('company', models.CharField(default=' ', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, default='510')),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True)),
                ('image', models.ImageField(default='images/store/nigne.png', upload_to='images/store/')),
                ('facebook', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('instagram', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('twitter', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('youtube', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='Enable', max_length=10)),
                ('slug', models.SlugField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/store/')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setting')),
            ],
        ),
    ]
