# Generated by Django 3.1.4 on 2021-01-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='caption',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='group',
            field=models.CharField(max_length=150, null=True, verbose_name='Banner Group'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], max_length=10),
        ),
    ]
