# Generated by Django 3.1.4 on 2021-01-15 13:22

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(default='Nigne', max_length=150, null=True)),
                ('status', models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='Enable', max_length=10)),
                ('caption', models.CharField(default='Nigne', max_length=150, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image_w', models.PositiveIntegerField(default=0)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='avatars')),
                ('sort_order', models.SmallIntegerField(blank=True, default=0)),
            ],
        ),
    ]
