# Generated by Django 3.1.4 on 2021-01-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210116_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='caption',
            field=models.CharField(default=1, max_length=150, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banners',
            name='group',
            field=models.CharField(default=1, max_length=150, verbose_name='Banner Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banners',
            name='link',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banners',
            name='sort_order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banners',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='Disable', max_length=10),
        ),
    ]
