# Generated by Django 3.1.4 on 2021-01-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settinglang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('ar', 'العربية')], max_length=6),
        ),
    ]
