# Generated by Django 3.1.4 on 2021-01-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(default='Nigne', max_length=150, null=True)),
                ('status', models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='Enable', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='banners',
            name='banner_name',
        ),
        migrations.RemoveField(
            model_name='banners',
            name='status',
        ),
        migrations.AddField(
            model_name='banners',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banner_group', to='core.bannergroup'),
            preserve_default=False,
        ),
    ]
