# Generated by Django 3.1.4 on 2021-01-26 17:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210125_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='about',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='title',
        ),
        migrations.RemoveField(
            model_name='settinglang',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='settinglang',
            name='description',
        ),
        migrations.RemoveField(
            model_name='settinglang',
            name='references',
        ),
        migrations.AddField(
            model_name='settinglang',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='settinglang',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settinglang',
            name='company',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settinglang',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='keywords',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], max_length=6),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='title',
            field=models.CharField(default='Nigne', max_length=150, null=True),
        ),
    ]
