# Generated by Django 3.1.4 on 2021-01-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210116_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], max_length=10),
        ),
    ]
