# Generated by Django 3.1.4 on 2021-01-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210115_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannergroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bannergroup',
            name='owner',
        ),
    ]
