# Generated by Django 3.1.4 on 2021-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210115_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='parent',
        ),
        migrations.AddField(
            model_name='bannergroup',
            name='banner',
            field=models.ManyToManyField(related_name='banner_group', to='core.Banners'),
        ),
    ]
