# Generated by Django 3.1.4 on 2021-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210115_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannergroup',
            name='banner',
        ),
        migrations.AddField(
            model_name='banners',
            name='banner',
            field=models.ManyToManyField(related_name='banner_group', to='core.BannerGroup'),
        ),
    ]
