# Generated by Django 3.1.4 on 2021-01-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210116_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='banner',
        ),
        migrations.DeleteModel(
            name='BannerGroup',
        ),
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
