# Generated by Django 3.1.4 on 2021-01-16 00:38

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210116_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(default='Nigne', max_length=150, null=True)),
                ('status', models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default='Enable', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='Nigne', max_length=150, null=True, verbose_name='Title')),
                ('link', models.URLField(blank=True, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='avatars')),
                ('sort_order', models.SmallIntegerField(blank=True, default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_group', to='core.bannergroup')),
            ],
        ),
    ]
