# Generated by Django 3.1.4 on 2021-01-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210113_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_active',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'Enable'), ('False', 'Disable')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='catalog.Tag'),
        ),
    ]
