# Generated by Django 3.1.4 on 2021-01-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_sellerproduct_seller'),
        ('vendors', '0004_auto_20210104_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.store'),
            preserve_default=False,
        ),
    ]
