# Generated by Django 3.1.4 on 2021-01-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210113_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AlterField(
            model_name='image',
            name='multiImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.product'),
        ),
    ]
