# Generated by Django 3.1.4 on 2021-01-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_remove_store_product'),
        ('catalog', '0004_sellerproduct_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendors.store'),
            preserve_default=False,
        ),
    ]
