# Generated by Django 3.1.4 on 2020-12-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201228_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='m_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
