# Generated by Django 3.1.4 on 2020-12-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201228_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='m_image',
            field=models.ImageField(default='/static/images/2.jpg', null=True, upload_to='images/'),
        ),
    ]
