# Generated by Django 3.1.4 on 2021-01-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210113_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='images/2.jpg', null=True, upload_to='images/'),
        ),
    ]
