# Generated by Django 3.1.4 on 2021-01-14 17:24

import catalog.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210114_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=catalog.models.models.get_image_filename, verbose_name='Image'),
        ),
    ]
