# Generated by Django 3.1.4 on 2020-12-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
