# Generated by Django 3.1.4 on 2021-01-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210114_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='images/2.jpg', null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='images/2.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='images/2.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='images/2.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(default='images/2.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image6',
            field=models.ImageField(default='images/2.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='images/2.jpg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
