# Generated by Django 3.1.4 on 2020-12-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201230_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'Enable'), ('False', 'Disable')], default='', max_length=10, verbose_name='status'),
        ),
    ]
