# Generated by Django 3.1.4 on 2020-12-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20201230_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
