# Generated by Django 3.1.4 on 2021-01-10 15:44

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nigne', max_length=150, null=True)),
                ('keywords', models.CharField(default=' ', max_length=255, null=True)),
                ('company', models.CharField(default=' ', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, default='510')),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True, unique=True)),
                ('image', models.ImageField(default='images/store/nigne.png', upload_to='images/store/')),
                ('facebook', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('instagram', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('twitter', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('youtube', models.URLField(blank=True, default='', max_length=50, null=True)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=10)),
                ('slug', models.SlugField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
