# Generated by Django 3.1.4 on 2021-01-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Enable', 'Enable')], default='Enable', max_length=10),
        ),
    ]
