# Generated by Django 3.1.4 on 2021-01-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20210105_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='product',
        ),
    ]
